name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: test
        run: yarn test
